# Generated by Django 4.2.5 on 2023-11-19 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена')),
                ('time', models.IntegerField(default=7, verbose_name='Срок выполнения')),
                ('due_date', models.IntegerField(default=28, verbose_name='Срок поддержки')),
                ('image', models.ImageField(upload_to='services')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Deleted')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(1, 'Зарегистрирован'), (2, 'Проверяется'), (3, 'Принято'), (4, 'Отказано'), (5, 'Удалено')], max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 11, 19, 10, 41, 8, 488826, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(null=True, verbose_name='Дата завершения')),
                ('services', models.ManyToManyField(null=True, to='maintenance.service', verbose_name='Сервисы')),
            ],
        ),
    ]
