# Generated by Django 4.2.7 on 2023-11-28 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_order_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 13, 35, 21, 291436, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
