# Generated by Django 4.2.7 on 2023-12-16 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0002_alter_order_options_remove_service_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 14, 32, 54, 275475, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
