# Generated by Django 4.2.7 on 2023-12-17 15:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0004_service_status_alter_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_moderator',
            field=models.ForeignKey(blank=True, db_column='id_moderator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_it', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_it', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 15, 38, 9, 895946, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
