# Generated by Django 4.2.7 on 2023-12-21 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0008_remove_order_id_user_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 10, 13, 57, 589703, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 10, 13, 57, 589703, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'), null=True, verbose_name='Дата формирования'),
        ),
    ]
