# Generated by Django 4.2.7 on 2023-12-25 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0010_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.IntegerField(null=True, verbose_name='Фактический срок выполнения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 22, 48, 15, 613252, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
