# Generated by Django 4.2.7 on 2023-12-25 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0011_order_deadline_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 23, 17, 59, 746546, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.CharField(null=True, verbose_name='Фактический срок выполнения заказа'),
        ),
    ]
