# Generated by Django 4.2.7 on 2023-12-27 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0012_alter_order_date_created_alter_order_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 7, 24, 56, 10828, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
